### ISSUE TITLE
Đánh giá bài tập cuối kì

### ISSUE THREAD

**Issue by KhanhNguyen4999** [KhanhNguyen4999/LTKHDL_FinalProject#1]

**Comment by KhanhNguyen4999** [comment]
Bài làm của mình vẫn còn chưa hoàn thiện. Nhưng sườn bài cũng đã xong. Cám ơn rất nhiều nếu có bạn nào góp ý giùm mình bài làm.

**Comment by ducanh2505** [comment]
Chào Khánh.
Mìn thấy bài làm của bạn khá là hay, bạn phân tích khá là đầy đủ các cột và thuộc tính trong tập dữ liệu. Tuy nhiên mình có một vài góp ý nhỏ như sau: 
- Có một vài biểu đồ bạn đã nhầm tiêu đề của 2 trục tọa độ (vd như biểu đồ province with the most region_1 bạn nhầm 2 trục)
- Bạn có thể giải thích thêm về biểu đồ Point By Province được không? mình chưa hiểu lắm về kết luận của bạn
Chúc bạn hoàn thiện đồ án một cách tốt nhất

**Comment by KhanhNguyen4999** [comment]
> Chào Khánh.
> Mìn thấy bài làm của bạn khá là hay, bạn phân tích khá là đầy đủ các cột và thuộc tính trong tập dữ liệu. Tuy nhiên mình có một vài góp ý nhỏ như sau:
> 
> * Có một vài biểu đồ bạn đã nhầm tiêu đề của 2 trục tọa độ (vd như biểu đồ province with the most region_1 bạn nhầm 2 trục)
> * Bạn có thể giải thích thêm về biểu đồ Point By Province được không? mình chưa hiểu lắm về kết luận của bạn
>   Chúc bạn hoàn thiện đồ án một cách tốt nhất

**Comment by KhanhNguyen4999** [comment]
Cám ơn Bạn rất nhiều. Mình sẽ điều chỉnh lại.
